In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

BRACKET INDEXING AND SELECTION

In [8]:
#GET A VALUE AT AN INDEX
arr[6]

6

In [7]:
#GET A VALUE IN A RANDGE
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
BROADCASTING
NUMPY ARRAYS DIFFER FROM A NORMAL PYTHON LIST BECAUSE OF THEIR ABILITY TO BROADCAST:

In [18]:
#SETTING A VALUE WITH INDEX RANGE (BROADCASTING)
arr[0:6]=100

#show
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [19]:
# Reset array, we'll see why i had to reset in 
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# important notes on slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
#Change slice
slice_of_arr[:] = 99

#Shownslice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# To get a copy, need to be explicit
arr_copy = arr.copy()

In [24]:
arr.copy()

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
INDEXING A 2D ARRAY (MATRICES )
THE GENERAL FORMAT IS arr_2d[row][col] or arr_2d[row,col].
I RECOMMMEND USUALLY USING THE COMMA NOTATIONFOR CLARITY.

In [25]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[2,2]

45

In [ ]:
FANCY INDEXING
FANCY INDEXING ALLOW YOU TO SELECT ENTIRE ROWS OR COLUMNS
OUT OF ORDER, TO SHOW THIS, LET'S QUICKLY BUILD OUT A NUMPY  ARRAY:

In [28]:
#Set up matrix
arr2d = np.zeros((10,10))

In [29]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
#lenght of array
arr_length = arr2d.shape[1]

In [31]:
arr_length

10

In [32]:
#Set up array
for i in range(arr_length):
    arr2d[i] = i
    
    arr2d

In [33]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
Fancy indexing allows the following.

In [36]:
arr2d[[2,3,4,6,8,9]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [37]:
#ALLOWS IN ANY ORDER
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
SELECTION 
 Let's briefly go over how to use brackets for selection based off of comparison operators.

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr> 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr > 4

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])